# Generated by Django 5.2.8 on 2026-02-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Kitobxonlik madaniyati'), (2, '5 muhim tashabbus'), (3, "Akademik o'zlashtirish (GPA)"), (4, 'Odob-axloq va dress-kod'), (5, "Ko'rik-tanlov va olimpiadalar"), (6, 'Darslardagi davomat'), (7, "Ma'rifat darslari"), (8, 'Volontyorlik va jamoat ishlari'), (9, 'Madaniy tashriflar'), (10, "Sport va sog'lom turmush"), (11, "Boshqa ma'naviy faollik")])),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('proof_file', models.FileField(upload_to='social_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
