# Generated by Django 5.2.8 on 2025-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_badges_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='seen',
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='badge',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='badges/proofs/'),
        ),
        migrations.AddField(
            model_name='badge',
            name='xp_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, help_text='Mutaxassislik / yo‘nalish', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='university_full',
            field=models.CharField(blank=True, help_text='To‘liq nom: Toshkent Axborot Texnologiyalari Universiteti', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='university_short',
            field=models.CharField(blank=True, help_text='Qisqa nom: TATU, TSUE va hokazo', max_length=255),
        ),
    ]
