# Generated by Django 5.2.8 on 2026-03-02 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_academicyear_socialachievement_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialachievement',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.academicyear'),
        ),
    ]
