# Generated by Django 5.2.8 on 2025-11-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_text_message_body_rename_read_message_seen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='seen',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='text',
        ),
    ]
