# Generated by Django 5.2.8 on 2026-03-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_socialachievement_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='global_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
