# Generated by Django 5.2.8 on 2026-03-13 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_global_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('category', models.CharField(choices=[('state', 'Davlat'), ('private', 'Xususiy'), ('international', 'Xalqaro')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.scholarship')),
            ],
        ),
    ]
