# Generated by Django 5.2.8 on 2026-03-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_announcement_benefits_announcement_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='meta',
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('international_cert', 'International Certificate'), ('national_cert', 'National Certificate'), ('intl_article', 'International Article'), ('rep_article', 'Republic Article'), ('activity', 'Social activity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='xp_count',
            field=models.IntegerField(default=0),
        ),
    ]
